title: "Cklamb70-learner-blog"
author: cklamb70
email: leokentlimited@outlook.com
description:  This is a blog spot to help me learn basic conding concepts. I am working towards being able to build a portfolio that will be marketable in the future.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-merlot
